// MAPPATURA STATUS HTTP IN CASO DI ERRORE
const errorStatusMap = {
    VALIDATION_ERROR: 400,
    CLOUDINARY_FAILURE: 400,
    BUSINESS_ERROR: 409,
    AUTH_ERROR: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    SCHEMA_ERROR: 500,
    MONGO_ERROR: 500,
    SERVER_ERROR: 500,
    CLOUDINARY_ERROR: 500,
};

export default errorStatusMap;
